Fix DPI support to declare in the Verilog files
The link stage passes '-dpi' to the vsim link script, to indicate to
use DPI, instead of the script looking for a 'dpi_declaration.v' file.
The Modelsim/Questa script is updated to work with DPI; along with the
Verilator script.  All other scripts now detect the flag and error
(that they don't yet support DPI).

The changes to the VProgram type are currently a draft -- the String
field should possibly be an abstract type.

The DPI declarations are updated to declare byte/int/longint as unsigned.

diff --git a/src/exec/bsc_build_vsim_iverilog b/src/exec/bsc_build_vsim_iverilog
--- a/src/exec/bsc_build_vsim_iverilog
+++ b/src/exec/bsc_build_vsim_iverilog
@@ -65,6 +65,8 @@ BSC_OTHER_ARGUMENTS=""
 
 VERBOSE="no"
 
+USEDPI="no"
+
 while [ $# -gt 0 ]; do
   if [ "${1%%.v}" != "$1" ]; then
     BSC_VERILOG_FILES="$BSC_VERILOG_FILES $1"
@@ -97,6 +99,8 @@ while [ $# -gt 0 ]; do
     BSC_VERILOG_OPTS="$BSC_VERILOG_OPTS $1"
   elif [ "$1" = "-verbose" ]; then
     VERBOSE="yes"
+  elif [ "$1" = "-dpi" ]; then
+    USEDPI="yes"
   else
     BSC_OTHER_ARGUMENTS="$BSC_OTHER_ARGUMENTS $1";
   fi
@@ -134,6 +138,11 @@ done
 
 # build VPI module if needed
 if [ -n "$BSC_VPI_FILES" ]; then
+  if [ "$USEDPI" == "yes" ] ; then
+    echo "ERROR: IVerilog linking does not yet support DPI."
+    echo "       Compile and link without the -use-dpi flag."
+    exit 1
+  fi
   echo "WARNING: IVerilog support for VPI is incomplete.  BSV designs using foreign"
   echo "         functions are not guaranteed to compile or simulate correctly."
   ## If CXX is set, use that.  Otherwise just use c++
diff --git a/src/exec/bsc_build_vsim_ncverilog b/src/exec/bsc_build_vsim_ncverilog
--- a/src/exec/bsc_build_vsim_ncverilog
+++ b/src/exec/bsc_build_vsim_ncverilog
@@ -63,6 +63,8 @@ BSC_OTHER_ARGUMENTS=""
 
 VERBOSE="no"
 
+USEDPI="no"
+
 while [ $# -gt 0 ]; do
   if [ "${1%%.v}" != "$1" ]; then
     BSC_VERILOG_FILES="$BSC_VERILOG_FILES $1"
@@ -94,6 +96,8 @@ while [ $# -gt 0 ]; do
     BSC_VERILOG_OPTS="$BSC_VERILOG_OPTS $1"
   elif [ "$1" = "-verbose" ]; then
     VERBOSE="yes"
+  elif [ "$1" = "-dpi" ]; then
+    USEDPI="yes"
   else
     BSC_OTHER_ARGUMENTS="$BSC_OTHER_ARGUMENTS $1";
   fi
@@ -134,6 +138,11 @@ fi
 
 # include VPI modules if supplied
 if [ -n "$BSC_VPI_FILES" ]; then
+  if [ "$USEDPI" == "yes" ] ; then
+    echo "ERROR: NCVerilog linking does not yet support DPI."
+    echo "       Compile and link without the -use-dpi flag."
+    exit 1
+  fi
   ## If CXX is set, use that.  Otherwise just use c++
   if [ "$CXX" = "" ]
   then
