Add testing of bsc-contrib to the CI

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -274,6 +274,8 @@ jobs:
           ccache --zero-stats --max-size 500M
           export PATH=/usr/lib/ccache:$PATH
 
+          # Use gold as the C++ linker
+          # for a moderate build-time speedup over ld.bfd
           REL=$(lsb_release -rs | tr -d .)
           if [ $REL -ge 1804 ]; then
               export LINKER=lld
@@ -282,19 +284,18 @@ jobs:
           fi
           export LDFLAGS="-Wl,-fuse-ld=$LINKER"
 
-          # Always archive logs, even if make fails (and terminates this script
-          # because it's invoked with :set -eo pipefile)
-          trap ./testsuite/archive_logs.sh EXIT
-
           # Use -O0 for significantly faster C++ compiles (which more
-          # than make up for slower simulations), and gold as the C++
-          # linked for a moderate build-time speedup over ld.bfd.
+          # than make up for slower simulations)
           export CXXFLAGS="-O0"
 
           if [ $REL -lt 1910 ]; then
               export TEST_SYSTEMC_INC=$HOME/systemc/include
               export TEST_SYSTEMC_LIB=$HOME/systemc/lib-linux64
           fi
+
+          # Always archive logs, even if make fails (and terminates this script
+          # because it's invoked with :set -eo pipefile)
+          trap ./testsuite/archive_logs.sh EXIT
 
           make -C testsuite
 
@@ -309,7 +310,7 @@ jobs:
         if: failure()
         uses: actions/upload-artifact@v1
         with:
-          name: logs-${{ matrix.os }}
+          name: test-logs-${{ matrix.os }}
           path: logs.tar.gz
 
   test-macOS:
@@ -351,13 +352,14 @@ jobs:
           ccache --zero-stats --max-size 500M
           export PATH=$(brew --prefix)/opt/ccache/libexec:$PATH
 
+          # Use -O0 for significantly faster C++ compiles (which more
+          # than make up for slower simulations).
+          export CXXFLAGS="-O0"
+
           # Always archive logs, even if make fails (and terminates this script
           # because it's invoked with :set -eo pipefile)
           trap ./testsuite/archive_logs.sh EXIT
 
-          # Use -O0 for significantly faster C++ compiles (which more
-          # than make up for slower simulations).
-          export CXXFLAGS="-O0"
           make -C testsuite \
                TEST_SYSTEMC_INC=$(brew --prefix systemc)/include \
                TEST_SYSTEMC_LIB=$(brew --prefix systemc)/lib
@@ -536,3 +538,171 @@ jobs:
         env:
           CCACHE_DIR: ${{ GITHUB.WORKSPACE }}/ccache
         run: ccache --show-stats
+
+  test-contrib-ubuntu:
+    strategy:
+      matrix:
+        os: [ ubuntu-16.04, ubuntu-18.04, ubuntu-20.04 ]
+      fail-fast: false
+    name: "Test bsc-contrib ${{ matrix.os }}"
+    runs-on: ${{ matrix.os }}
+    needs: build-ubuntu
+    steps:
+      - uses: actions/checkout@v2
+
+      - name: Install dependencies
+        shell: bash
+        run: "sudo .github/workflows/install_dependencies_testsuite_ubuntu.sh"
+
+      - name: Download bsc
+        uses: actions/download-artifact@v2
+        with:
+          name: ${{ matrix.os }} build
+      - name: Install bsc
+        run: "tar xzf inst.tar.gz"
+
+      - name: Download bsc-contrib
+        run: |
+          git clone --recursive https://github.com/B-Lang-org/bsc-contrib ../bsc-contrib
+
+      - name: Build and install bsc-contrib
+        run: |
+          export PATH=$PWD/../bsc/inst/bin:$PATH
+          make -C ../bsc-contrib/
+
+      # Restore previous ccache cache of compiled object files. Use a SHA
+      # in the key so that a new cache file is generated after every
+      # successful build, and have the restore-key use the most recent.
+      - name: CCache cache files
+        uses: actions/cache@v2
+        with:
+          path: ${{ GITHUB.WORKSPACE }}/ccache
+          key: test-contrib-${{ matrix.os }}-ccache-${{ github.sha }}
+          restore-keys: |
+            test-contrib-${{ matrix.os }}-ccache-
+
+      - name: Run bsc-contrib tests
+        env:
+          CCACHE_DIR: ${{ GITHUB.WORKSPACE }}/ccache
+        run: |
+          # Use ccache to avoid recompiling generated .cxx every run.
+          ccache --zero-stats --max-size 500M
+          export PATH=/usr/lib/ccache:$PATH
+
+          # Use gold as the C++ linker
+          # for a moderate build-time speedup over ld.bfd
+          REL=$(lsb_release -rs | tr -d .)
+          if [ $REL -ge 1804 ]; then
+              export LINKER=lld
+          else
+              export LINKER=gold
+          fi
+          export LDFLAGS="-Wl,-fuse-ld=$LINKER"
+
+          # Use -O0 for significantly faster C++ compiles (which more
+          # than make up for slower simulations).
+          export CXXFLAGS="-O0"
+
+          # Copy the bsc-contrib tests into place
+          cp -r ../bsc-contrib/testing/bsc.contrib testsuite/
+
+          # Inform the tests of the path to the bsc-contrib libraries
+          export BSCCONTRIBDIR=$PWD/../bsc-contrib/inst
+
+          # Always archive logs, even if make fails (and terminates this script
+          # because it's invoked with :set -eo pipefile)
+          trap ./testsuite/archive_logs.sh EXIT
+
+          make -C testsuite/bsc.contrib check
+
+      # Show ccache stats so we can see what the hit-rate is like.
+      - name: CCache stats
+        env:
+          CCACHE_DIR: ${{ GITHUB.WORKSPACE }}/ccache
+        run: ccache --show-stats
+
+      # Save test logs on failure so we can diagnose
+      - name: Archive test logs
+        if: failure()
+        uses: actions/upload-artifact@v1
+        with:
+          name: test-contrib-logs-${{ matrix.os }}
+          path: logs.tar.gz
+
+  test-contrib-macOS:
+    strategy:
+      matrix:
+        os: [ macos-10.15 ]
+    name: "Test bsc-contrib ${{ matrix.os }}"
+    runs-on: ${{ matrix.os }}
+    needs: build-macos
+    steps:
+      - uses: actions/checkout@v2
+      - name: Install dependencies
+        shell: bash
+        run: ".github/workflows/install_dependencies_testsuite_macos.sh"
+
+      - name: Download bsc
+        uses: actions/download-artifact@v2
+        with:
+          name: macos-10.13+ build
+      - name: Install bsc
+        run: "tar xzf inst.tar.gz"
+
+      - name: Download bsc-contrib
+        run: |
+          git clone --recursive https://github.com/B-Lang-org/bsc-contrib ../bsc-contrib
+
+      - name: Build and install bsc-contrib
+        run: |
+          export PATH=$PWD/../bsc/inst/bin:$PATH
+          make -C ../bsc-contrib/
+
+      # Restore previous ccache cache of compiled object files. Use a SHA
+      # in the key so that a new cache file is generated after every
+      # successful build, and have the restore-key use the most recent.
+      - name: CCache cache files
+        uses: actions/cache@v2
+        with:
+          path: ${{ GITHUB.WORKSPACE }}/ccache
+          key: test-contrib-${{ matrix.os }}-ccache-${{ github.sha }}
+          restore-keys: |
+            test-contrib-${{ matrix.os }}-ccache-
+
+      - name: Run bsc-contrib tests
+        env:
+          CCACHE_DIR: ${{ GITHUB.WORKSPACE }}/ccache
+        run: |
+          # Use ccache to avoid recompiling generated .cxx every run.
+          ccache --zero-stats --max-size 500M
+          export PATH=$(brew --prefix)/opt/ccache/libexec:$PATH
+
+          # Use -O0 for significantly faster C++ compiles (which more
+          # than make up for slower simulations).
+          export CXXFLAGS="-O0"
+
+          # Copy the bsc-contrib tests into place
+          cp -r ../bsc-contrib/testing/bsc.contrib testsuite/
+
+          # Inform the tests of the path to the bsc-contrib libraries
+          export BSCCONTRIBDIR=$PWD/../bsc-contrib/inst
+
+          # Always archive logs, even if make fails (and terminates this script
+          # because it's invoked with :set -eo pipefile)
+          trap ./testsuite/archive_logs.sh EXIT
+
+          make -C testsuite/bsc.contrib check
+
+      # Show ccache stats so we can see what the hit-rate is like.
+      - name: CCache stats
+        env:
+          CCACHE_DIR: ${{ GITHUB.WORKSPACE }}/ccache
+        run: ccache --show-stats
+
+      # Save test logs on failure so we can diagnose
+      - name: Archive test logs
+        if: failure()
+        uses: actions/upload-artifact@v2
+        with:
+          name: test-contrib-logs-${{ matrix.os }}
+          path: logs.tar.gz
